on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
      - uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.INTEGRATIONS_FNM_SLACK_WEBHOOK_URL }}
        if: ${{ steps.release-please.outputs.release_created }}
        with:
          payload: |
            {
              "project_name": "${{ github.repository.full_name }}",
              "version_string": "${{ steps.release-please.outputs.major }}.${{ steps.release-please.outputs.minor }}.${{ steps.release-please.outputs.patch }}",
              "description": "${{ github.repository.description }",
              "link": "${{ github.repository.html_url }}"
            }
        